### PR TITLE
Makefile refactor

### PR DESCRIPTION
**Pull request by terrycain**
Rearranged many of the makefiles.
Created Debian packaging information for Ubuntu 14.04 in separate empty branch so keep things nice and separated. Should also get rid nearly all of the lintian errors on the deb files too ;)

Will test it out in a VM soon but in the near future we _should_ have a possibly usable PPA. And with all the changes it should allow me to make RPMs this time.

@lah7 mind cloning this and double checking that `make` still works.

### CODE REVIEW

**Comment by terrycain** [comment]
Once this one is good to go I'll force my other branch upstream. Cant create pull requests into non-existent branches.

**Comment by lah7** [comment]
Can confirm `make` works fine on Ubuntu 15.10 with these new changes. :+1:

**Comment by terrycain** [comment]
Wicked I will test the install of the deb's it creates on my VM tomorrow perhaps and then push up some 14.04 debs to a PPA.

**Comment by terrycain** [comment]
Some make targets have been renamed. Soz if this breaks for some people but its _intended_ to make packaging easier (though slightly more complicated)

**Pull request merged**
