### PR TITLE
Add support for Razer Blade Stealth

### PR DESCRIPTION
**Pull request by storborg**
This adds driver-level support for the Blade Stealth internal laptop keyboard backlighting, similar in protocol to the Blackwidow Chroma. Controlling the lid logo LED is also supported (on/off only, no brightness control).

Stuff that works and has been tested:
- modes: breath, reactive, spectrum, static, wave, off
- brightness control
- getting the device type (reported as "Razer Blade Stealth").
- setting logo on/off

Stuff that still doesn't seem to work, but is still enabled:
- getting the serial number (unless I have a bizarrely low serial number)
- ``set_key_row``
- ``temp_clear_row``

Stuff that I haven't attempted at all yet, but has clues that it might be possible:
- setting the default function of the media keys (F1-F12 / volume, etc)
- setting brightness independently for AC power vs. desktop power state

### CODE REVIEW

**Comment by terrycain** [comment]
Looks good, edit the wiki page accordingly ;).

Would you mind sending me a zip of some screenshots of what Synapse looks like when used on the Stealth? And also a list of features in synapse that don't currently work?

Try out `scripts/driver/keyboard_keys.py` you will need to modify the 2 paths at the top of the file with the right path to the stealth, then you should be able to keep tapping enter and keys _should_ light up one by one

**Comment by storborg** [comment]
Do you just mean adding the logo stuff to the keyboard driver page? Just did that.

In ``keyboard_keys.py``, only the initial row seems to do anything, and it triggers a gaming mode of some kind (WASD in red, etc). I tried out using ``set_key_row`` directly with and without adjustments for keyboard size, and it doesn't seem to work.

These are the features in the Synapse app that don't currently work / aren't implemented:
- You can set whether the default behavior of F keys is F1-F12 or media keys.
- You can set independent global brightness values for mains power vs battery power.
- There is one additional behavior mode which triggers expanding LED activations on keyboard presses: enabling this mode causes a continuing flurry of USB traffic, so my guess is that this is using some combination of individual key addressing and/or more sophisticated custom modes.
- You can assign different profiles which are then enabled by key combinations. No idea if this is happening in Windows userspace, the kernel, or the keyboard firmware itself.

**Comment by terrycain** [comment]
Ok the profiles I believe is in Windows. The ripple effect is done manually by Windows and not in hardware, could you get a dump of that as that might explain why key addressing doesn't work.

**Comment by storborg** [comment]
Picture time! Here's the Chroma tab in Synapse with list of effects:
synapse-effects

The ripple effect selected:
synapse-ripple

There's also a much more powerful configurator tool that I haven't played around with at all. I suspect this operates in userspace too.
synapse-chroma-configurator

Other tabs for configuring non-blinky stuff:
synapse-keyboard-tab
synapse-trackpad-tab
synapse-gaming-mode-tab
synapse-power-tab

**Comment by storborg** [comment]
Here's a dump of enabling the ripple mode, and then pressing one key. 
[set-ripple-mode-and-keypress.pcapng.gz](https://github.com/pez2001/razer_chroma_drivers/files/199970/set-ripple-mode-and-keypress.pcapng.gz)

**Comment by terrycain** [comment]
Cheers, will look at that tomorrow, 
Packet dump of brightness on battery slider
Packet dump of brightness plugged in slider
Packet dump of toggling between function keys and mulitmedia keys

should be able to add more then :wink:

**Comment by storborg** [comment]
Here's some more dumps.

---
[set-fkeys-to-function.pcapng.gz](https://github.com/pez2001/razer_chroma_drivers/files/200409/set-fkeys-to-function.pcapng.gz)
[set-fkeys-to-multimedia.pcapng.gz](https://github.com/pez2001/razer_chroma_drivers/files/200410/set-fkeys-to-multimedia.pcapng.gz)

---
For the brightness sliders I started in pure red static mode and adjusted the sliders to the min (numeric 33), normal (65), and bright (100) settings in Synapse.
[set-battery-brightness-min33.pcapng.gz](https://github.com/pez2001/razer_chroma_drivers/files/200412/set-battery-brightness-min33.pcapng.gz)
[set-battery-brightness-normal65.pcapng.gz](https://github.com/pez2001/razer_chroma_drivers/files/200415/set-battery-brightness-normal65.pcapng.gz)
[set-battery-brightness-bright100.pcapng.gz](https://github.com/pez2001/razer_chroma_drivers/files/200416/set-battery-brightness-bright100.pcapng.gz)
[set-pluggedin-brightness-min33.pcapng.gz](https://github.com/pez2001/razer_chroma_drivers/files/200417/set-pluggedin-brightness-min33.pcapng.gz)
[set-pluggedin-brightness-normal65.pcapng.gz](https://github.com/pez2001/razer_chroma_drivers/files/200418/set-pluggedin-brightness-normal65.pcapng.gz)
[set-pluggedin-brightness-bright100.pcapng.gz](https://github.com/pez2001/razer_chroma_drivers/files/200419/set-pluggedin-brightness-bright100.pcapng.gz)

---
I also investigated the settings on the 'Power' tab in Synapse, and the setting to disable lighting when on battery power sends some USB traffic (here) but doesn't seem to persist out of Windows. Here's that traffic:
[disable-lighting-off-on-battery.pcapng.gz](https://github.com/pez2001/razer_chroma_drivers/files/200420/disable-lighting-off-on-battery.pcapng.gz)
[enable-lighting-off-on-battery.pcapng.gz](https://github.com/pez2001/razer_chroma_drivers/files/200422/enable-lighting-off-on-battery.pcapng.gz)

**Pull request merged**
