### PR TITLE
Driver overhaul

### PR DESCRIPTION
**Pull request by terrycain**
Changed the structure of the driver's report and reflected those changes throughout the code. Have got the code to a state where lots of duplicate code can now be eliminated.

* Created a function to return a struct of the report with common defaults populated.
* Added file to return the keyboards firmware version. Mines `v1.1`
* Added read functionality on mode_game which returns 1 if its enabled, 0 otherwise
* Added read/write functionality for the macro_led. If 2 is written then it will flash.
* Added read functionality to the brightness so you can tell what level the keyboard is at.

@storborg and @lah7 and anyone else, mind testing out these new changes. I'm planning on removing lots of duplicated functions before I merge but just want to be sure I haven't broken anything thus far.

### CODE REVIEW

**Comment by storborg** [comment]
This isn't building for me, although I suspect it has more to do with distro issues (this is on up-to-date ubuntu 16.04) than in this branch. I haven't investigated any further yet, but does this look familiar?

```
$ sudo dpkg -i /tmp/razer-chroma-driver_1.0.0_amd64.deb 
Selecting previously unselected package razer-chroma-driver.
(Reading database ... 306521 files and directories currently installed.)
Preparing to unpack .../razer-chroma-driver_1.0.0_amd64.deb ...
Unpacking razer-chroma-driver (1.0.0) ...
Setting up razer-chroma-driver (1.0.0) ...
Loading new razer_chroma_driver-1.0.0 DKMS files...
Building only for 4.4.0-21-generic
Building initial module for 4.4.0-21-generic
ERROR (dkms apport): unable to determine source package for razer-chroma-driver
Error! Bad return status for module build on kernel: 4.4.0-21-generic (x86_64)
Consult /var/lib/dkms/razer_chroma_driver/1.0.0/build/make.log for more information.
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160415-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for dbus (1.10.6-1ubuntu3) ...
Processing triggers for systemd (229-4ubuntu4) ...
Processing triggers for ureadahead (0.100.0-19) ...
```

The contents of ``make.log`` is:
```
DKMS make.log for razer_chroma_driver-1.0.0 for kernel 4.4.0-21-generic (x86_64)
Fri Apr 22 08:49:57 PDT 2016
make: *** No rule to make target 'razer_drv_verbose'.  Stop.
```

**Comment by terrycain** [comment]
I've updated the make targets since that, I make some pretty major Makefile changes, try `make driver_verbose`

**Comment by terrycain** [comment]
Don't make a deb for this, just make the driver, and load razerkbd.ko with insmod and then manually bind and then test

**Comment by terrycain** [comment]
But yeah, I need to update the dkms file one sec.

**Comment by terrycain** [comment]
Should work with DKMS now.

**Comment by lah7** [comment]
Compiled, `make install`'d, rebooted. Keyboard driver and GUI utilities are still working as expected. No problems to report so far.

**Comment by terrycain** [comment]
@lah7 can you set the keyboard to static colour effect (using the app as this will pause the daemon's custom colour mode if its running). 

Then can you manually prod the driver with `echo -n '1' > mode_macro`. I think its called `mode_macro`, the one that's not called `macro_keys`. That should illuminate the macro led next to game mode. echoing `'0'` will turn off the led and `'2'`should make it flash.

**Comment by lah7** [comment]
Hm. `mode_macro` doesn't seem to be here?
```
$# ls /sys/bus/hid/drivers/razerkbd/0003:1532:0203.0003/
country      hidraw      mode_breath  mode_reactive  power              set_key_row     uevent
device_type  input       mode_custom  mode_spectrum  report_descriptor  subsystem
driver       macro_keys  mode_game    mode_static    reset              temp_clear_row
get_serial   modalias    mode_none    mode_wave      set_brightness     test
```

**Comment by terrycain** [comment]
You don't have get_firmware_version either. I assume the permission of set_brightness doesn't allow read?

**Comment by lah7** [comment]
Ah, I had generated a deb from `package_for_ubuntu.sh` instead of just `sudo make install` and interestingly, they're here now:
```
$ ls /sys/bus/hid/drivers/razerkbd/0003:1532:0203.0003$
country               hidraw       mode_custom    mode_spectrum      reset           test
device_type           input        mode_game      mode_static        set_brightness  uevent
driver                macro_keys   mode_macro     mode_wave          set_key_row
get_firmware_version  modalias     mode_none      power              subsystem
get_serial            mode_breath  mode_reactive  report_descriptor  temp_clear_row
```

`echo -n '1' > mode_macro` and `0` turns on/off as expected, but `2` doesn't flash.

**Comment by terrycain** [comment]
try setting brightness and then catting it. I did mess with the macro function and not test it but it seems my changes broke it, I shall modify it in a bit.

**Comment by terrycain** [comment]
@lah7 Mind trying again. Might still not work but am away from keyboard for a bit so can't test it myself.

**Comment by lah7** [comment]
Nope, still broken. Can confirm `echo`ing and `cat`ing `set_brightness` works too.

**Comment by terrycain** [comment]
arrgg, :rage:, cool, I shall investigate tomorrow, would probably be easier to seperate out the toggleing of on/off and the effect static/flashy to different files.

**Comment by terrycain** [comment]
OK :smile: I seperated it out. And it works for me but @lah7 I'd like a final test before I push on and do some hardcore refactoring. The `mode_macro` now only accepts `1`/`0` and should be `cat`able. `mode_macro_effect` should take `1`/`0` to make the macro LED static/blinking (though the LED must be on first).

**Comment by lah7** [comment]
Can confirm it's working. :+1: 

* `cat mode_macro` ... works.
* `echo -n '1' > mode_macro` ... starts blinking.
* `echo -n '0' > mode_macro_effect` ... makes it solid.
* `echo -n '1' > mode_macro_effect` ... starts blinking again.

**Comment by terrycain** [comment]
Wicked :+1:. Am working on reducing repeated functions now.

**Comment by terrycain** [comment]
Actually, I think this is enough work for now, its cleaner than it was :smile:

**Pull request merged**
