### PR TITLE
Added Razer Abyssus support

### PR DESCRIPTION
**Pull request by terrycain**
Added logo function and device type for Razer Abyssus.

### CODE REVIEW

**Comment by terrycain** [comment]
@claell can you test this patch.
Make the driver with `make driver_verbose`
Insert the kernel module with `insmod ./driver/razermouse.ko`

You then need to unbind the mouse from the generic-hid driver and bind it to the razermouse driver, look at the wiki page about setting up the keyboard driver (it still applies), start at binding the driver section, it should explain everything,

You also need to bind the correct device, there could be multiple, in `/sys/bus/hid/devices/`
They will look something like this.
`0003:1532:0042.0009  0003:1532:0042.000A  0003:1532:0042.000B`

You want to bind the device starting with `0003:1532:0042` and after the `.` pick the one with the lowest number. So in this case `0009`. 

Or if you use the `udevadm info` command from the wiki, you are after interface number 0

Once its binded what is the output of the following (substituting the number/id for the one on your system)
```
cd /sys/bus/hid/drivers/razermouse/0003:1532:0042.0009
ls -l
```

**Comment by claell** [comment]
Will do. Will this get simplified in the future/are these steps needed in order to make the driver work out of the box?

**Comment by claell** [comment]
I am in /sys/bus/hid/drivers/hid-generic and tried `echo -n "0003:1532:0042.0001" > unbind` Unfortunately it says I am not allowed to do this.

**Comment by terrycain** [comment]
@claell Yes, currently it is simplified to work out of the box but testing things manually is more involved and slightly more complicated.

When runnnig the `echo` command are you the root user?

**Comment by claell** [comment]
Ok.

At first I tried `echo -n "0003:1532:0042.0001" > unbind` after that also `sudo echo -n "0003:1532:0042.0001" > unbind`

Both failed. Error message is `bash: unbind: Keine Berechtigung`

**Comment by claell** [comment]
similar to https://bugs.launchpad.net/ubuntu/+source/sudo/+bug/288964?

**Comment by claell** [comment]
`sudo -i` and then the commands again worked.

**Comment by claell** [comment]
Now I cannot use `echo -n "0003:1532:0042.0001" > bind` in `/sys/bus/hid/drivers/razermouse/`
Message: `-bash: echo: Schreibfehler: Kein passendes Gerät gefunden.`

It works in the other folder, however.

**Comment by terrycain** [comment]
Hmmm, not sure why it wont bind.

Are you sure you have the correct `razermouse_driver.h` file? Does it contain the line
```
#define USB_DEVICE_ID_RAZER_ABYSSUS 0x0042
```

What is the output of `lsusb --verbose -d 1532:0042`

**Comment by claell** [comment]
The `razermouse_driver.h` does not contain the Abyssus line.

I just cloned the git repo. But I see this is not merged yet. So how do I get the correct version?

**Comment by claell** [comment]
I downloaded the repository as zip from https://github.com/terrycain/razer_drivers/tree/abyssus now and it works.

**Comment by claell** [comment]
```
root@clel-ubuntu-ThinkPad-T400:/sys/bus/hid/drivers/razermouse# cd /sys/bus/hid/drivers/razermouse/0003\:1532\:0042.0001
root@clel-ubuntu-ThinkPad-T400:/sys/bus/hid/drivers/razermouse/0003:1532:0042.0001# ls -l
insgesamt 0
-r--r--r-- 1 root root 4096 Mai  4 20:02 country
-r--r--r-- 1 root root 4096 Mai  4 20:02 device_type
lrwxrwxrwx 1 root root    0 Mai  4 20:00 driver -> ../../../../../../../../bus/hid/drivers/razermouse
drwxr-xr-x 3 root root    0 Mai  4 20:00 hidraw
drwxr-xr-x 3 root root    0 Mai  4 20:00 input
-r--r--r-- 1 root root 4096 Mai  4 20:02 modalias
-rw-rw---- 1 root root 4096 Mai  4 20:02 mode_logo
drwxr-xr-x 2 root root    0 Mai  4 20:02 power
-r--r--r-- 1 root root 4096 Mai  4 20:02 report_descriptor
lrwxrwxrwx 1 root root    0 Mai  4 19:45 subsystem -> ../../../../../../../../bus/hid
-rw-r--r-- 1 root root 4096 Mai  4 19:45 uevent

```

**Comment by claell** [comment]
Hope it helps

**Comment by terrycain** [comment]
Looks good. :), Now see that file `mode_logo`

If you do this, it should turn the logo on
`echo -n '1' > ./mode_logo`
And this should turn it off
`echo -n '0' > ./mode_logo`

**Comment by terrycain** [comment]
If not then you might have the wrong device binded (should be interface 0 returned by the udevadm info command from the wiki)

**Comment by claell** [comment]
It works.

**Comment by terrycain** [comment]
Have added udev rules. That will make it bind automatically. Haven't added the refresh rate as of yet as am lazy but also need to add that for my Mamba so ill do that when I do my Mamba. The Abyssus and my Mamba arn't on the controller app or the daemon yet.

**Comment by claell** [comment]
Ok.

**Pull request merged**
