### PR TITLE
Replaced keyboard editor

### PR DESCRIPTION
**Pull request by terrycain**
Added a new keyboard editor.

@lah7 mind testing?

### CODE REVIEW

**Comment by lah7** [comment]
Sure, will check out the changes tomorrow.

You should be able to push to my fork first if you'd like me to test / raise issues with code before going ahead with the pull request here, that's up to you.

**Comment by terrycain** [comment]
I might do that at some point but then there might be inconsistencies between your repo and the main one.

**Comment by lah7** [comment]
I usually `git pull --rebase upstream master` to keep things clean. We could push to an "unstable" branch if code isn't quite ready for general usage.

----------
**Seems to be in working order, except:**
 1. **Picker no longer works.**
  * I see you left this as a `TODO`.
 2. Spacebar and FN key colourable on new profiles on BlackWidow Chroma, but not when editing existing profiles.

**Comment by terrycain** [comment]
1) Will look at the picker, completely forgot about that, meant to fix that.
2) Ahh, yeah on the newer keyboards they are editable, shall copy the disable commands to that part.

I think I might create an unstable/testing branch next time.

**Comment by terrycain** [comment]
@lah7 another test please ;). Should all be working now.

**Comment by lah7** [comment]
All working good. I found some more code for cleaning up earlier and made a few improvements to the keyboard SVG. Consider pulling these in too:

* Clean-up = 74028492f14906711ac1d061740ae853f04f2383
* Keyboard Improvements = 031ccddee8ab1e9442299b314ce129b9d57cf550

**Comment by terrycain** [comment]
Good spot, done the clean up. Will double check the SVG works but then all should be good

**Pull request merged**
