### PR TITLE
Refactored dynamic.c

### PR DESCRIPTION
**Pull request by TheKiwi5000**
I refactored dynamic.c so the name convention is in English (sorry for that). Originally it was meant to be used in scripts, hence the lack of interactive mode.

### CODE REVIEW

**Comment by terrycain** [comment]
Hmmmm, merge conflicts, joy. I'll have a look at it later unless pez beats me to it.

**Comment by TheKiwi5000** [comment]
Sorry for merge conflicts, I am using git via terminal. I could not sync my
fork with the original. This is my first ever collaborative programming, so
I'm still learning.
29 sty 2016 11:52 "Terry Cain" <notifications@github.com> napisał(a):

**Comment by lah7** [comment]
It's likely because the repo has been renamed from `razer_blackwidow_chroma_drivers` to `razer_chroma_drivers` that's causing sync/rebase problems. Consider updating your `remote` URLs.

**Comment by terrycain** [comment]
@lah7 I believe GitHub redirects you to the new repo so old remotes *should* work.

**Comment by terrycain** [comment]
Merged

**Comment by TheKiwi5000** [comment]
So, how do i set the remotes?
I did `git clone` my fork to my working dir.
I currently have my fork set as origin for both fetching and pushing. What do i set to get my fork up to date with this one?

**Comment by lah7** [comment]
To list all remotes in your repo:
`git remote -v`

To add this one (called `upstream`):
`git remote add upstream https://github.com/pez2001/razer_chroma_drivers.git`

If you need to rename it:
`git remote rename <old url> <new url>`

To merge the latest commits into your `master`:
`git pull upstream master`

But if I have no changes, I like to keep things clean by rebasing my copy of the repo with `upstream`, like it's a clean fork:
`git pull --rebase upstream`

**Pull request merged**
