### PR TITLE
GUI and Tray Improvements

### PR DESCRIPTION
**Pull request by lah7**
### Preferences Reset Required
The `preferences.json` has been restructured to now support groups. As a result, any previous preferences **will need to be reset**! *(Thank goodness there were only 3 options!)* While the application will write these new values if non-existent, it's a good idea to click "Reset Preferences" in the options so you have a clean file.

---------
### Tray Applet
 * Add profiles menu.
 * Add option to open configuration tool.
 * Ability to use the static logo, animated logo or system *(DBus)* icon.
 * Supports custom icons (by specifying a path to an image)

### Chroma GUI / Preferences
 * Can set "start-up" options, effective if the Tray Applet automatically starts when you log on.
 * Can set your preferred colours, retained across sessions.
 * Can set the start effect, brightness, a profile and whether the macro key functionality should be enabled.
 * Current primary/secondary colours are retained across pages.

### Code Changes
 * Migrated 'Preferences' and 'Profiles' to their own modules.
 * Minor fixes to some code areas.
 * Fix for PyGIWarnings.
 * Preferences keeps a note of its version, to warn if large changes happen in future.

### CODE REVIEW

**Comment by terrycain** [comment]
Would it be worth checking for legacy preferences.json and bringing up warning?

**Comment by lah7** [comment]
The preferences module will print a notice in the terminal about using a "newer format , but the only thing these changes will do for existing users is "deactivate" them. The apps/module automatically writes a fallback value if none exist.

**Comment by terrycain** [comment]
Ok cool, I take it you tested this thoroughly, with the latest daemon etc...

**Comment by lah7** [comment]
Not as extensive as the latest daemon (any changes in the last 11 days), but there's no reason for it to cause problems as these are purely UI / `preferences.json` changes). Everything works as it should, I always test changes before committing. :+1:

**Pull request merged**
