### PR TITLE
Possibly added more stealth options

### PR DESCRIPTION
**Pull request by terrycain**
Attempted to add fn_toggle
Attempted to fix individual key and brightness.

Don't merge, its a work in progress.

### CODE REVIEW

**Comment by storborg** [comment]
Yep, this works for individual keys (other than the rows being too long). Worth noting that the up/down keys are a little weird: left is 5:12, up is 5:13, right is 5:14, down is 5:15.

**Comment by storborg** [comment]
Brightness also works-- it actually worked before this patch as well, but this branch might have better scaling? Not sure there.

**Comment by storborg** [comment]
``set_fn_toggle`` also works correctly. Writing a "0" makes the default function F1-F12, writing a "1" makes the default function the media keys.

**Comment by terrycain** [comment]
This all makes me happy. I will need to investigate why the brightness
works both times, hmmm. The rows being too long is due to the python app as
that's set to 22 keys per row I think. Will work on this more in the
morning.

**Pull request merged**
